# Generated by Django 4.2.1 on 2023-07-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentcreate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
