# Generated by Django 4.2.1 on 2023-07-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_comment_commentcreate'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='previewPost',
            field=models.CharField(default='', max_length=512),
        ),
    ]
